export const REQUEST_FEATCH_BANNERS = "REQUEST_FEATCH_BANNERS"
export const SUCCESS_FEATCH_BANNERS = "SUCCESS_FEATCH_BANNERS"
export const    FAIL_FEATCH_BANNERS    = "FAIL_FEATCH_BANNERS"


export const REQUEST_FETCH_ALL_CATEGORY_BANNERS = "REQUEST_FETCH_ALL_CATEGORY_BANNERS"
export const FETCH_ALL_CATEGORY_BANNERS_SUCCESS = "FETCH_ALL_CATEGORY_BANNERS_SUCCESS"
export const FETCH_ALL_CATEGORY_BANNERS_FAIL = "FETCH_ALL_CATEGORY_BANNERS_FAIL"
export const CLEAR_ERRORS    = "CLEAR_ERRORS"