export const FETCH_ADDRESS_FORM = "FETCH_ADDRESS_FORM"
export const FETCH_ADDRESS_FORM_SUCCESS = "FETCH_ADDRESS_FORM_SUCCESS"
export const FETCH_ADDRESS_FORM_FAIL = "FETCH_ADDRESS_FORM_FAIL"
export const CLEAR_ERRORS    = "CLEAR_ERRORS"


export const FETCH_ALL_OPTIONS_REQUEST = "FETCH_ALL_OPTIONS_REQUEST";
export const FETCH_ALL_OPTIONS_SUCCESS = "FETCH_ALL_OPTIONS_SUCCESS";
export const FETCH_ALL_OPTIONS_FAIL = "FETCH_ALL_OPTIONS_FAIL";



export const FETCH_ALL_COUPONS_REQUEST = "FETCH_ALL_COUPONS_REQUEST";
export const FETCH_ALL_COUPONS_SUCCESS = "FETCH_ALL_COUPONS_SUCCESS";
export const FETCH_ALL_COUPONS_FAIL = "FETCH_ALL_COUPONS_FAIL";

export const FETCH_DISCLAIMERS_REQUEST = "FETCH_DISCLAIMERS_REQUEST";
export const FETCH_DISCLAIMERS_SUCCESS = "FETCH_DISCLAIMERS_SUCCESS";
export const FETCH_DISCLAIMERS_FAIL = "FETCH_DISCLAIMERS_FAIL";


export const FETCH_TERMS_AND_CONDITIONS = "FETCH_TERMS_AND_CONDITIONS";
export const FETCH_TERMS_AND_CONDITIONS_SUCCESS = "FETCH_TERMS_AND_CONDITIONS_SUCCESS";
export const FETCH_TERMS_AND_CONDITIONS_FAIL = "FETCH_TERMS_AND_CONDITIONS_FAIL";


export const FETCH_PRIVACY_AND_POLICY = "FETCH_PRIVACY_AND_POLICY";
export const FETCH_PRIVACY_AND_POLICY_SUCCESS = "FETCH_PRIVACY_AND_POLICY_SUCCESS";
export const FETCH_PRIVACY_AND_POLICY_FAIL = "FETCH_PRIVACY_AND_POLICY_FAIL";

export const FETCH_FAQS = "FETCH_FAQS";
export const FETCH_FAQS_SUCCESS = "FETCH_FAQS_SUCCESS";
export const FETCH_FAQS_FAIL = "FETCH_FAQS_FAIL";

export const FETCH_COUPON_BANNER_REQUEST = "FETCH_COUPON_BANNER_REQUEST";
export const FETCH_COUPON_BANNER_SUCCESS = "FETCH_COUPON_BANNER_SUCCESS";
export const FETCH_COUPON_BANNER_FAIL = "FETCH_COUPON_BANNER_FAIL";