export const REQUEST_PRODUCTS = "REQUEST_PRODUCTS"
export const SUCCESS_PRODUCTS = "SUCCESS_PRODUCTS"
export const FAIL_PRODUCTS = "FAIL_PRODUCTS"


export const REQUEST_All_PRODUCTS = "REQUEST_ALL_PRODUCTS"
export const SUCCESS_All_PRODUCTS = "SUCCESS_ALL_PRODUCTS"
export const FAIL_All_PRODUCTS = "FAIL_ALL_PRODUCTS"



export const REQUEST_SINGLE_PRODUCTS = "REQUEST_SINGLE_PRODUCTS"
export const SUCCESS_SINGLE_PRODUCTS = "SUCCESS_SINGLE_PRODUCTS"
export const FAIL_SINGLE_PRODUCTS = "FAIL_SINGLE_PRODUCTS"
export const CLEAR_ERRORS    = "CLEAR_ERRORS"


export const REQUEST_RANDOM_PRODUCT = "REQUEST_RANDOM_PRODUCT";
export const SUCCESS_RANDOM_PRODUCT = "SUCCESS_RANDOM";
export const FAIL_RANDOM_PRODUCT = "FAIL_RANDOM_PRODUCT";


export const REQUEST_OPTIONS = "REQUEST_OPTIONS"
export const SUCCESS_OPTIONS = "SUCCESS_OPTIONS"
export const FAIL_OPTIONS = "FAIL_OPTIONS"



