export const REQUEST_USER_NO = "REQUEST_USER_NO"
export const SUCCESS_USER_NO = "SUCCESS_USER_NO"
export const FAIL_USER_NO    = "FAIL_USER_NO"
export const REQUEST_USER = "REQUEST_USER"
export const SUCCESS_USER = "SUCCESS_USER"
export const FAIL_USER    = "FAIL_USER   "
export const REQUEST_VERIFY_OTP = "REQUEST_VERIFY_OTP"
export const SUCCESS_VERIFY_OTP = "SUCCESS_VERIFY_OTP"
export const FAIL_VERIFY_OTP    = "FAIL_VERIFY_OTP   "
export const REQUEST_RESEND_OTP = "REQUEST_RESEND_OTP"
export const SUCCESS_RESEND_OTP = "SUCCESS_RESEND_OTP"
export const FAIL_RESEND_OTP    = "FAIL_RESEND_OTP"

export const REQUEST_UPDATE_USER    = "REQUEST_UPDATE_USER"
export const SUCCESS_UPDATE_USER    = "SUCCESS_UPDATE_USER"
export const FAIL_UPDATE_USER    = "FAIL_UPDATE_USER"

export const REQUEST_UPDATE_ADDRESS = "REQUEST_UPDATE_ADDRESS"
export const SUCCESS_UPDATE_ADDRESS = "SUCCESS_UPDATE_ADDRESS"
export const FAIL_UPDATE_ADDRESS = "FAIL_UPDATE_ADDRESS"

export const REQUEST_ALL_ADDRESS  = "REQUEST_ALL_ADDRESS";
export const SUCCESS_ALL_ADDRESS  = "SUCCESS_ALL_ADDRESS";
export const FAIL_ALL_ADDRESS  = "FAIL_ALL_ADDRESS";

export const SUCCESS_LOGOUT = "SUCCESS_LOGOUT"
export const FAIL_LOGOUT = "FAIL_LOGOUT"
export const REQUEST_UPDATE_DETAILS_USER    = "REQUEST_UPDATE_DETAILS_USER   "
export const SUCCESS_UPDATE_DETAILS_USER    = "SUCCESS_UPDATE_DETAILS_USER   "
export const FAIL_UPDATE_DETAILS_USER    = "FAIL_UPDATE_DETAILS_USER   "



export const REGISTER_USER_DATA = "REGISTER_USER_DATA"
export const SUCCESS_REGISTER_USER = "SUCCESS_REGISTER_USER"
export const FAIL_REGISTER_USER = "FAIL_REGISTER_USER"
export const LOGIN_USER_DATA = "LOGIN_USER_DATA"
export const SUCCESS_LOGIN_USER = "SUCCESS_LOGIN_USER"
export const FAIL_LOGIN_USER = "FAIL_LOGIN_USER"
export const LOGOUT_USER = "LOGOUT_USER"
export const GET_USER_DATA = "GET_USER_DATA"
export const SUCCESS_GET_USER = "SUCCESS_GET_USER"
export const FAIL_GET_USER = "FAIL_GET_USER"
export const CLEAR_ERRORS    = "CLEAR_ERRORS"