export const REQUEST_FETCH_VIDEO_REVIEWS = "REQUEST_FETCH_VIDEO_REVIEWS";
export const SUCCESS_FETCH_VIDEO_REVIEWS = "SUCCESS_FETCH_VIDEO_REVIEWS";
export const FAIL_FETCH_VIDEO_REVIEWS = "FAIL_FETCH_VIDEO_REVIEWS";
